name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Setup Node.js 📦
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies 🔧
      run: npm ci

    - name: Debug vars/secrets presence ✨
      run: |
        echo "Test present? => ${{ vars.Test != '' }}"
        echo "RENDER_API_URL present? => ${{ vars.RENDER_API_URL != '' }}"
        echo "GH_TOKEN present? => ${{ secrets.GH_TOKEN != '' }}"
        echo "GITHUB_TOKEN present? => ${{ secrets.GITHUB_TOKEN != '' }}"

      
    - name: Build for production 🏗️
      run: npm run build
      env:
        # URL de la API desplegada en Render
        VITE_API_BASE_URL: ${{ secrets.RENDER_API_URL }}
        VITE_APP_ENVIRONMENT: production
        VITE_GITHUB_USER: DiamondStalker

    - name: Deploy to GitHub Pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./dist
